// Factory intake — storyboard generator.
//
// One fixture set, one renderer per surface, one entry per state; every state is rendered at
// desktop (1280) and mobile (390). Run from this directory: node generate.mjs
// Never edit index.html by hand. Screen ids s1..sN are stable review anchors once review starts.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const OUT = path.dirname(fileURLToPath(import.meta.url))

// ── prototype id ────────────────────────────────────────────────────────
// The page and the committed review comments must agree on this id: prototype.js drops a
// comments.js whose `prototypeId` differs from the page's `data-prototype-id`. This generator
// owns it — it writes comments.js when the file is missing and refuses to run when the
// committed one disagrees, so a rename cannot quietly turn a reviewer's export into
// "no comments yet". Change it here (and rename the directory) in one step.
const PROTOTYPE_ID = 'factory-intake'

const commentsFile = (prototypeId) => `/* Committed prototype review operations.
 *
 * Do not edit this file by hand. Reviewers add comments in the prototype,
 * choose "Export for repository", replace this file, and commit it. Operations
 * are append-only and identified by id; delete operations are tombstones, so
 * merging reviewer exports cannot silently resurrect deleted feedback.
 *
 * \`prototypeId\` must stay equal to PROTOTYPE_ID in generate.mjs.
 */
window.__OM_PROTOTYPE_COMMENTS__ = {
  version: 2,
  prototypeId: '${prototypeId}',
  operations: []
};
`

// The id as the file declares it. Single or double quotes: the scaffold writes the object
// literal above, "Export for repository" writes JSON. Comments are stripped first so a mention
// of the field in the file's header cannot be read as the declaration, and the lookbehind keeps
// a key that merely ends in `prototypeId` from matching.
const ID_IN_COMMENTS = /(?<![\w$])["']?prototypeId["']?\s*:\s*["']([^"']*)["']/

function declaredPrototypeId(source) {
  const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '')
  const found = ID_IN_COMMENTS.exec(code)
  return found ? found[1] : null
}

function syncComments() {
  const file = path.join(OUT, 'comments.js')
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, commentsFile(PROTOTYPE_ID))
    console.log('wrote comments.js for', PROTOTYPE_ID)
    return
  }
  const declared = declaredPrototypeId(fs.readFileSync(file, 'utf8'))
  if (declared === null) {
    throw new Error(`comments.js declares no prototypeId. It must read '${PROTOTYPE_ID}' — the id this page is generated with. Fix it, or delete comments.js to have it written afresh (this discards any committed review comments).`)
  }
  if (declared !== PROTOTYPE_ID) {
    throw new Error(`comments.js is for prototype '${declared}', but this page is generated as '${PROTOTYPE_ID}'. The prototype would load and silently ignore its own committed review comments. Set prototypeId in comments.js to '${PROTOTYPE_ID}' (or fix PROTOTYPE_ID here), then re-run.`)
  }
}

// ── icons (Lucide paths; add what the surface needs) ────────────────────
const ICONS = {
  home: '<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M9 22V12h6v10"/>',
  search: '<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',
  plus: '<path d="M5 12h14"/><path d="M12 5v14"/>',
  'chevron-right': '<path d="m9 18 6-6-6-6"/>',
  'chevron-down': '<path d="m6 9 6 6 6-6"/>',
  'chevron-left': '<path d="m15 18-6-6 6-6"/>',
  menu: '<line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/>',
  more: '<circle cx="5" cy="12" r="1.75"/><circle cx="12" cy="12" r="1.75"/><circle cx="19" cy="12" r="1.75"/>',
  check: '<path d="M20 6 9 17l-5-5"/>',
  'check-circle': '<circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/>',
  'alert-circle': '<circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" y2="12"/><line x1="12" x2="12.01" y1="16" y2="16"/>',
  warn: '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
  info: '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>',
  x: '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
  bot: '<path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2"/><path d="M20 14h2"/><path d="M15 13v2"/><path d="M9 13v2"/>',
  user: '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  sparkles: '<path d="M9.94 15.5A2 2 0 0 0 8.5 14.06l-6.14-1.58a.5.5 0 0 1 0-.96L8.5 9.94A2 2 0 0 0 9.94 8.5l1.58-6.14a.5.5 0 0 1 .96 0L14.06 8.5a2 2 0 0 0 1.44 1.44l6.14 1.58a.5.5 0 0 1 0 .96l-6.14 1.58a2 2 0 0 0-1.44 1.44l-1.58 6.14a.5.5 0 0 1-.96 0z"/>',
  wrench: '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>',
  send: '<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',
  paperclip: '<path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48"/>',
  loader: '<path d="M21 12a9 9 0 1 1-6.219-8.56"/>',
  clock: '<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>',
  pr: '<circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><path d="M13 6h3a2 2 0 0 1 2 2v7"/><line x1="6" x2="6" y1="9" y2="21"/>',
  external: '<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
  eye: '<path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',
  inbox: '<polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/>',
  kanban: '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M8 7v7"/><path d="M12 7v4"/><path d="M16 7v9"/>',
  folder: '<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/>',
  bell: '<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>',
  activity: '<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>',
  workflow: '<rect width="8" height="8" x="3" y="3" rx="2"/><path d="M7 11v4a2 2 0 0 0 2 2h4"/><rect width="8" height="8" x="13" y="13" rx="2"/>',
  flask: '<path d="M10 2v7.53a2 2 0 0 1-.21.9L4.72 20.55a1 1 0 0 0 .9 1.45h12.76a1 1 0 0 0 .9-1.45l-5.07-10.13A2 2 0 0 1 14 9.53V2"/><path d="M8.5 2h7"/><path d="M7 16h10"/>',
  package: '<path d="m7.5 4.27 9 5.15"/><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/>',
  shield: '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="M12 8v4"/><path d="M12 16h.01"/>',
  rotate: '<path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/>',
  message: '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
  link: '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>',
  'sig-3': '<path d="M2 20h.01"/><path d="M7 20v-4"/><path d="M12 20v-8"/><path d="M17 20V8"/>',
  'sig-2': '<path d="M2 20h.01"/><path d="M7 20v-4"/><path d="M12 20v-8"/>',
  'sig-1': '<path d="M2 20h.01"/><path d="M7 20v-4"/>',
  urgent: '<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M12 8v4"/><path d="M12 16h.01"/>',
  filter: '<polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>',
  child: '<polyline points="15 10 20 15 15 20"/><path d="M4 4v7a4 4 0 0 0 4 4h12"/>',
  minimize: '<polyline points="4 14 10 14 10 20"/><polyline points="20 10 14 10 14 4"/><line x1="14" x2="21" y1="10" y2="3"/><line x1="3" x2="10" y1="21" y2="14"/>',
  ban: '<circle cx="12" cy="12" r="10"/><path d="m4.9 4.9 14.2 14.2"/>',
  globe: '<circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/>',
  'x-circle': '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>',
  pencil: '<path d="M21.17 6.81a1 1 0 0 0-3.99-3.99L3.84 16.17a2 2 0 0 0-.5.83l-1.32 4.35a.5.5 0 0 0 .62.62l4.35-1.32a2 2 0 0 0 .83-.5z"/>',
}
const strokeFill = (name) => (name === 'more' ? 'fill="currentColor" stroke="none"' : 'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"')
const sprite = () =>
  `<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>${Object.entries(ICONS)
    .map(([k, d]) => `<symbol id="ic-${k}" viewBox="0 0 24 24" ${strokeFill(k)}>${d}</symbol>`)
    .join('')}</defs></svg>`
export const ic = (name) => `<svg aria-hidden="true"><use href="#ic-${name}"/></svg>`
export const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

// ── fixtures (fictional) ────────────────────────────────────────────────
// Northwind Furniture runs its catalog and staff in Open Mercato; project WEB is its website repo.
const people = {
  MK: { name: 'Maya Kowalczyk', ini: 'MK' },
  TL: { name: 'Tomasz Lis', ini: 'TL' },
  AN: { name: 'Ada Nowak', ini: 'AN' },
}
const AGENT = 'Factory agent'
const project = { key: 'WEB', name: 'Company website', repo: 'github.com/northwind-furniture/website' }

const STATUSES = [
  { id: 'open', label: 'Open', accent: 'var(--status-neutral-icon)', count: 'badge-neutral' },
  { id: 'queued', label: 'Queued', accent: 'var(--status-info-icon)', count: 'badge-info' },
  { id: 'in_design', label: 'In design', accent: 'var(--brand-violet)', count: 'badge-pink' },
  { id: 'in_progress', label: 'In progress', accent: 'var(--status-warning-icon)', count: 'badge-warning' },
  { id: 'in_review', label: 'In review', accent: 'var(--status-pink-icon)', count: 'badge-pink' },
]
const STATUS_BADGE = {
  open: ['badge-neutral', 'Open'], queued: ['badge-info', 'Queued'], in_design: ['badge-pink', 'In design'],
  in_progress: ['badge-warning', 'In progress'], in_review: ['badge-pink', 'In review'],
  done: ['badge-success', 'Done'], rejected: ['badge-neutral', 'Rejected'], failed: ['badge-error', 'Failed'],
}

const T = {
  web15: { ref: 'WEB-15', title: 'Fix broken Privacy link in the footer', status: 'open', priority: 'low', assignee: 'TL' },
  web14: { ref: 'WEB-14', title: 'Add a size guide to dining table pages', status: 'open', priority: 'medium', assignee: 'MK',
    body: ['Customers keep asking whether our tables fit 6 or 8 chairs. Add a size guide block to every dining table product page.', ['Seats per table size, from the catalog attribute <code>seats</code>', 'Room clearance drawing (the PDF from design, attached)', 'Same block on the Polish and German sites']] },
  web13: { ref: 'WEB-13', title: 'Update Oak dining table price on the product page', status: 'queued', priority: 'high', assignee: 'MK', delegate: true, run: 'starting', source: 'chat' },
  web11: { ref: 'WEB-11', title: 'Add EU shipping calculator to checkout', status: 'in_design', priority: 'high', assignee: 'MK', delegate: true, run: 'awaiting', waiting: '18 min',
    body: ['Checkout shows shipping only after the address step. Show an estimate for EU countries on the cart page.', ['Estimate by country and parcel size', 'Same number as the final checkout price, or explain why not', 'No new carrier contract']] },
  web10: { ref: 'WEB-10', title: 'Newsletter signup on blog pages', status: 'in_progress', priority: 'medium', assignee: 'TL', delegate: true, run: 'running', runFor: '12 min' },
  web9: { ref: 'WEB-9', title: 'Publish product page: Linden bench', status: 'in_review', priority: 'medium', assignee: 'MK', delegate: true, run: 'complete', pr: '#48',
    body: ['The Linden bench went live in the catalog on 16 Sep. Publish its product page on the website with the gallery, dimensions and care notes.', ['Same template as the Oak dining table page', 'Gallery from the catalog media, in catalog order', 'Price and availability from the storefront API, not hard-coded']] },
  web8: { ref: 'WEB-8', title: 'Replace hero image on the home page', status: 'in_review', priority: 'low', assignee: 'AN', pr: '#46' },
  web16: { ref: 'WEB-16', title: 'Add alt text to Linden bench gallery images', status: 'open', priority: 'medium', assignee: 'MK', parent: 'WEB-9' },
  web6: { ref: 'WEB-6', title: 'Sync stock badges with the warehouse feed', status: 'failed', priority: 'medium', assignee: 'TL',
    reason: 'Run failed in step "build slice 1 of 2": CI failed twice (fix round used). tests/stock-badge.spec.ts: expected "In stock", got "Low stock" for SKU NW-OAK-180.',
    body: ['Stock badges on product pages lag the warehouse by a day. Read them from the warehouse feed instead.', ['Badge updates within 15 minutes of a stock change', '"Low stock" below 3 units']] },
}
const closed = { done: 1, rejected: 1, failed: 1 }
const boardTasks = [T.web15, T.web14, T.web16, T.web13, T.web11, T.web10, T.web9, T.web8]

// ── small parts ─────────────────────────────────────────────────────────
const avatar = (key, size = 'avatar-sm') => `<span class="avatar ${size}" title="${esc(people[key].name)}">${people[key].ini}</span>`
const agentMark = (lg) => `<span class="tk-agent${lg ? ' tk-agent-lg' : ''}" title="${AGENT}">${ic('bot')}</span>`
const prio = (p) => {
  const map = { urgent: ['urgent', 'Urgent'], high: ['sig-3', 'High'], medium: ['sig-2', 'Medium'], low: ['sig-1', 'Low'] }
  return `<span class="tk-prio tk-prio-${p}" title="${map[p][1]} priority">${ic(map[p][0])}</span>`
}
const statusBadge = (s) => `<span class="badge ${STATUS_BADGE[s][0]}"><span class="dot"></span>${STATUS_BADGE[s][1]}</span>`
function runBadge(run, extra = '') {
  const m = {
    starting: ['badge-neutral', `${ic('loader')} Starting…`],
    stalled: ['badge-error', `${ic('alert-circle')} Stalled`],
    running: ['badge-success', `<span class="pulse"></span> Running${extra ? ' · ' + extra : ''}`],
    awaiting: ['badge-warning', `${ic('inbox')} Needs decision`],
    complete: ['badge-success', `${ic('check')} Run complete`],
    failed: ['badge-error', `${ic('x-circle')} Run failed`],
  }[run]
  return `<span class="badge tk-run ${m[0]}">${m[1]}</span>`
}
const prChip = (pr) => `<span class="tk-pr">${ic('pr')}${esc(pr)}</span>`

function card(t, { focus, stalled } = {}) {
  const run = stalled && t.run === 'starting' ? 'stalled' : t.run
  return `<div class="kcard tk-card${focus ? ' is-focus' : ''}${run === 'stalled' ? ' is-error' : ''}">
    <div class="tk-card-top"><span class="tk-ref">${t.ref}</span>${prio(t.priority)}</div>
    <div class="tk-card-title">${esc(t.title)}</div>
    ${t.parent ? `<span class="tk-parent">${ic('child')} follow-up of ${t.parent}</span>` : ''}
    ${run === 'stalled' ? `<div class="t-hint" style="color:var(--status-error-text)">No run picked this up for 2 min.</div><div class="tk-card-actions"><button class="btn btn-outline btn-xs">Un-delegate</button><button class="btn btn-ghost btn-xs">Details</button></div>` : ''}
    <div class="tk-card-foot">
      <span style="display:inline-flex;align-items:center;gap:0.375rem">${t.delegate ? agentMark() : ''}${t.delegate ? runBadge(run, t.runFor) : ''}${t.pr ? prChip(t.pr) : ''}</span>
      ${avatar(t.assignee)}
    </div>
  </div>`
}

// ── shell ───────────────────────────────────────────────────────────────
function frame({ url, mobile, body }) {
  return `<div class="frame ${mobile ? 'sb-frame-mobile' : 'sb-frame-desktop'}">
    <div class="frame-bar"><div class="frame-dots"><i></i><i></i><i></i></div><span class="frame-url">${esc(url)}</span><span class="sb-frame-label">${mobile ? 'mobile · 390' : 'desktop · 1280'}</span></div>
    ${body}
  </div>`
}
const both = (render) => `<div class="sb-pair">${render(false)}${render(true)}</div>`

function sidebar(active) {
  const item = (id, icon, label, count) => `<a class="nav-item${active === id ? ' active' : ''}">${ic(icon)}${label}${count ? `<span class="count">${count}</span>` : ''}</a>`
  return `<aside class="sidebar">
    <div class="sidebar-brand"><span class="brand-mark">NF</span>Northwind Furniture</div>
    <div class="sidebar-search">${ic('search')}Search…</div>
    <nav class="sidebar-nav">
      <div class="nav-group">Work</div>
      <div class="nav-items">${item('tasks', 'kanban', 'Tasks')}${item('projects', 'folder', 'Projects')}</div>
      <div class="nav-group">Agents</div>
      <div class="nav-items">${item('caseload', 'inbox', 'Caseload', 3)}${item('processes', 'workflow', 'Processes')}${item('playground', 'flask', 'Playground')}</div>
      <div class="nav-group">Catalog</div>
      <div class="nav-items">${item('products', 'package', 'Products')}</div>
    </nav>
  </aside>`
}
function topbar(crumbs, mobile) {
  if (mobile) {
    return `<header class="topbar tk-topbar-mobile">
      <div class="topbar-left"><button class="icon-btn">${ic('menu')}</button><span class="crumbs"><span class="here">${esc(crumbs[crumbs.length - 1])}</span></span></div>
      <div class="topbar-right"><button class="icon-btn" title="AI (⌘L)"><span class="ai-dot"></span></button><button class="icon-btn">${ic('bell')}</button>${avatar('MK', 'avatar')}</div>
    </header>`
  }
  return `<header class="topbar">
    <div class="topbar-left"><nav class="crumbs">${ic('home')}${crumbs.map((c, i) => `${ic('chevron-right')}<span class="${i === crumbs.length - 1 ? 'here' : ''}">${esc(c)}</span>`).join('')}</nav></div>
    <div class="topbar-right">
      <button class="btn btn-ghost btn-sm tk-ai-btn"><span class="ai-dot"></span>AI<span class="kbd">⌘L</span></button>
      <div class="topbar-search">${ic('search')}Search… <span class="kbd" style="margin-left:auto">⌘K</span></div>
      <button class="icon-btn">${ic('bell')}<span class="badge-count">2</span></button>
      ${avatar('MK', 'avatar')}
    </div>
  </header>`
}
// overlay: html placed over the page (desktop drawer/modal) or replacing it (mobile sheet)
function shell({ url, mobile, nav, crumbs, page, overlay, overlayKind, dock, tall }) {
  const scrim = overlay && !mobile ? (overlayKind === 'modal' ? 'modal-scrim' : 'drawer-scrim') : ''
  const content = overlay && mobile ? overlay : page
  const height = tall ? `min-height:${tall}` : ''
  return frame({
    url, mobile,
    body: `<div class="${scrim}" style="position:relative">
      <div class="app ${mobile ? 'tk-app-mobile' : dock ? 'tk-app-dock' : ''}" style="${mobile ? 'min-height:844px' : height}">
        ${mobile ? '' : sidebar(nav)}
        <div class="main">${mobile && overlay ? '' : topbar(crumbs, mobile)}${content}</div>
        ${dock && !mobile ? dock : ''}
      </div>
      ${overlay && !mobile ? overlay : ''}
    </div>`,
  })
}

// ── tasks board ─────────────────────────────────────────────────────────
function boardToolbar(filters = [], mobile) {
  if (mobile) {
    return `<div class="tk-toolbar"><span class="tk-project">${ic('folder')}WEB · ${project.name}${ic('chevron-down')}</span><button class="btn btn-outline btn-icon">${ic('filter')}</button></div>`
  }
  const chip = (label, active) => `<span class="chip${active ? ' chip-active' : ' chip-dashed'}">${active ? '' : ic('plus')}${esc(label)}${active ? ` ${ic('x')}` : ''}</span>`
  const f = new Set(filters.map((x) => x.split(':')[0]))
  return `<div class="tk-toolbar">
    <span class="tk-project">${ic('folder')}WEB · ${project.name}${ic('chevron-down')}</span>
    <span class="tk-search">${ic('search')}Search tasks…</span>
    ${filters.map((x) => chip(x, true)).join('')}
    ${['Assignee', 'Has delegate', 'Priority'].filter((x) => !f.has(x)).map((x) => chip(x)).join('')}
    <span class="grow"></span>
    <span class="tk-hint"><span class="kbd">D</span> delegate · <span class="kbd">↵</span> open</span>
  </div>`
}
function boardHead(mobile, disabled) {
  return `<div class="page-head"><div><h1 class="t-page-title">Tasks</h1>${mobile ? '' : `<p>Everything the team and the factory are working on.</p>`}</div>
    <div class="page-actions"><button class="btn btn-primary${disabled ? ' is-disabled' : ''}">${ic('plus')}New task</button></div></div>`
}
function board({ tasks = boardTasks, focus, stalled, filters, noResults, mobileCol = 'in_design' }, mobile) {
  if (noResults) {
    return `<div class="page">${boardHead(mobile)}${boardToolbar(filters, mobile)}
      ${mobile ? `<div class="tk-strip">${filters.map((x) => `<span class="chip chip-active">${esc(x)} ${ic('x')}</span>`).join('')}</div>` : ''}
      <div class="empty"><div class="empty-icon">${ic('filter')}</div><b>No tasks match these filters</b><span class="muted">Nothing in WEB is assigned to Tomasz Lis, delegated, and urgent.</span><button class="btn btn-outline btn-sm">Clear filters</button></div></div>`
  }
  if (mobile) {
    const col = STATUSES.find((s) => s.id === mobileCol)
    return `<div class="page" style="gap:1rem">${boardHead(true)}${boardToolbar([], true)}
      <div class="tk-strip">${STATUSES.map((s) => `<span class="chip${s.id === mobileCol ? ' chip-active' : ''}">${s.label} ${tasks.filter((t) => t.status === s.id).length}</span>`).join('')}<span class="chip">Closed 3</span></div>
      <div class="tk-lane">${tasks.filter((t) => t.status === col.id).map((t) => card(t, { focus: t.ref === focus, stalled })).join('')}</div></div>`
  }
  const cols = STATUSES.map((s) => {
    const items = tasks.filter((t) => t.status === s.id)
    return `<div class="tk-col"><div class="kcol-head"><div class="kcol-accent" style="background:${s.accent}"></div>
      <div class="kcol-title"><span class="name">${s.label}</span><span class="kcol-count badge ${s.count}">${items.length}</span></div></div>
      <div class="kcol-body">${items.map((t) => card(t, { focus: t.ref === focus, stalled })).join('')}${s.id === 'open' ? `<button class="kquick">${ic('plus')}New task</button>` : ''}</div></div>`
  }).join('')
  return `<div class="page">${boardHead(false)}${boardToolbar(filters)}
    <div class="tk-board">${cols}<div class="tk-closed" title="Show closed">${ic('chevron-left')}<span class="v">Closed · ${closed.done + closed.rejected + closed.failed}</span></div></div></div>`
}

// ── task drawer ─────────────────────────────────────────────────────────
function prop(label, value, extra = '') { return `<div class="tk-prop"><dt>${label}</dt><dd>${value}</dd>${extra}</div>` }
function drawer(t, o = {}, mobile) {
  const delegateValue = o.delegatePicker === 'open'
    ? `<span class="tk-picker is-open">No delegate${ic('chevron-down')}</span>`
    : o.delegatePicker === 'disabled'
      ? `<span class="tk-picker is-disabled">No delegate${ic('chevron-down')}</span>`
      : t.delegate ? `${agentMark()}${AGENT}` : `<span class="tk-picker">No delegate${ic('chevron-down')}</span>`
  const pop = o.delegatePicker === 'open' ? `<div class="popover tk-pop">
      <div class="menu-item is-active">${agentMark()}<div><b>${AGENT}</b><div class="t-hint">Researches, sizes, designs for your approval, then opens a PR. Starts a run of <code>factory.deliver</code>.</div></div></div>
      <div class="menu-item">${ic('ban')}<div>No delegate</div></div>
      <div class="tk-pop-foot">You stay the assignee. You can take it back until the plan is sized.</div></div>` : ''
  const reason = o.delegatePicker === 'disabled' ? `<div class="tk-reason">Delegating to an agent needs the <code>tasks.delegate</code> permission. Ask an admin, or ask Tomasz Lis to delegate it.</div>` : ''
  const side = `<dl class="tk-props" style="margin:0">
      ${prop('Status', statusBadge(t.status))}
      ${t.delegate ? prop('Run', runBadge(t.run, t.runFor)) : ''}
      ${prop('Project', `WEB · ${project.name}`)}
      ${prop('Assignee', `${avatar(t.assignee)}${people[t.assignee].name}`)}
      ${prop('Delegate', delegateValue, pop + reason)}
      ${prop('Priority', `${prio(t.priority)}${t.priority[0].toUpperCase() + t.priority.slice(1)}`)}
      ${prop('Parent', t.parent || '<span class="muted">—</span>')}
      ${prop('Created by', `${avatar(o.createdBy || t.assignee)}${people[o.createdBy || t.assignee].name}`)}
    </dl>`
  const body = t.body ? `<div class="tk-body"><p>${t.body[0]}</p><ul>${t.body[1].map((b) => `<li>${b}</li>`).join('')}</ul></div>` : ''
  const section = (title, html) => html ? `<section><h3 class="tk-section-title">${title}</h3>${html}</section>` : ''
  const links = o.links ? `<div class="tk-links">${o.links.map((l) => `<div class="tk-link">${ic(l.icon)}<div class="grow"><div>${l.label}</div>${l.sub ? `<div class="t-hint">${l.sub}</div>` : ''}</div>${l.right || ''}</div>`).join('')}</div>` : ''
  const timeline = o.timeline ? `<ol class="tk-timeline">${o.timeline.map((e) => `<li><span class="dot${e.on ? ' on' : ''}"></span><span>${e.text}</span><time>${e.at}</time></li>`).join('')}</ol>` : ''
  const comments = o.comments ? `<div class="stack-3">${o.comments.map((c) => `<div class="tk-comment">${avatar(c.who)}<div><span class="who">${people[c.who].name}</span><span class="when">${c.at}</span><p>${c.text}</p></div></div>`).join('')}<textarea class="textarea" placeholder="Add a comment…" style="min-height:3rem"></textarea></div>` : ''
  const main = `<div class="stack-6">${o.alert || ''}${body}${section('Links', links)}${section('Follow-ups', o.followups || '')}${section('Timeline', timeline)}${section('Comments', comments)}</div>`
  const head = `<div class="drawer-head">
      ${mobile ? `<button class="icon-btn">${ic('chevron-left')}</button>` : ''}
      <div class="grow"><div style="display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap"><span class="tk-ref">${t.ref}</span>${statusBadge(t.status)}${t.delegate ? runBadge(t.run, t.runFor) : ''}</div><h2 class="tk-drawer-title">${esc(t.title)}</h2></div>
      <button class="icon-btn">${ic('more')}</button>${mobile ? '' : `<button class="icon-btn">${ic('x')}</button>`}
    </div>`
  const foot = o.foot ? `<div class="drawer-foot">${o.foot}</div>` : ''
  const grid = mobile ? `<div class="tk-drawer-grid">${side}${main}</div>` : `<div class="tk-drawer-grid">${main}${side}</div>`
  return mobile
    ? `<div class="tk-sheet">${head}<div class="drawer-body">${grid}</div>${foot}${o.toast || ''}</div>`
    : `<div class="drawer tk-drawer">${head}<div class="drawer-body">${grid}</div>${foot}</div>${o.toast || ''}`
}

// ── new task dialog ─────────────────────────────────────────────────────
function newTaskDialog(mobile) {
  const fields = `
    <div class="field"><label>Project <span class="req">*</span></label><div class="tk-picker" style="height:2.25rem">WEB · ${project.name}${ic('chevron-down')}</div></div>
    <div class="field"><label>Title <span class="req">*</span></label><input class="input" value="Add a size guide to dining table pages" /></div>
    <div class="field"><label>Description</label><textarea class="textarea" style="min-height:7rem">Customers keep asking whether our tables fit 6 or 8 chairs. Add a size guide block to every dining table product page.

- Seats per table size, from the catalog attribute \`seats\`
- Room clearance drawing (PDF attached)</textarea><span class="t-hint">Agents read this as instructions. Say what done looks like.</span></div>
    <div class="${mobile ? 'stack-4' : 'form-grid form-grid-2'}" style="gap:1rem">
      <div class="field"><label>Priority</label><div class="segmented"><button>Low</button><button aria-selected="true">Medium</button><button>High</button><button>Urgent</button></div></div>
      <div class="field"><label>Assignee</label><div class="tk-picker" style="height:2.25rem"><span style="display:inline-flex;gap:0.375rem;align-items:center">${avatar('MK')}Maya Kowalczyk (you)</span>${ic('chevron-down')}</div></div>
    </div>`
  if (mobile) {
    return `<div class="tk-sheet"><div class="drawer-head"><button class="icon-btn">${ic('x')}</button><div class="grow"><h2 class="tk-drawer-title" style="margin:0.25rem 0 0">New task</h2></div></div>
      <div class="drawer-body">${fields}</div><div class="drawer-foot" style="flex-direction:column"><button class="btn btn-primary" style="width:100%">Create task</button><button class="btn btn-outline" style="width:100%">Cancel</button></div></div>`
  }
  return `<div class="modal"><div class="modal-head"><h2 style="margin:0;font-size:1.125rem;font-weight:600">New task</h2><p class="muted" style="margin:0.25rem 0 0;font-size:0.875rem">It gets the next reference in the project, WEB-17.</p></div>
    <div class="modal-body">${fields}</div>
    <div class="modal-foot"><span class="t-hint"><span class="kbd">⌘</span><span class="kbd">↵</span> create</span><div style="display:flex;gap:0.5rem"><button class="btn btn-outline">Cancel</button><button class="btn btn-primary">Create task</button></div></div></div>`
}

// ── Caseload (orchestrator's own page; illustrative) ────────────────────
function caseload(mobile) {
  const q = [
    { active: true, agent: AGENT, wait: '18 min', head: 'Approve design: EU shipping calculator', ref: 'WEB-11', risk: ['badge-warning', 'Medium risk'], conf: '82%' },
    { agent: 'Legal reviewer gate', wait: '1 h', head: 'Terms page: new returns window wording', ref: 'WEB-12', risk: ['badge-error', 'Legal text'], conf: '—' },
    { agent: AGENT, wait: '3 h', head: 'Size: Import customer reviews widget', ref: 'SHOP-4', risk: ['badge-neutral', 'Low risk'], conf: '64%' },
  ]
  const queue = `<div class="tk-pane">${q.map((r) => `<div class="tk-qrow${r.active ? ' is-active' : ''}">${agentMark(true)}<div class="grow" style="min-width:0">
      <div class="l1">${r.agent}<span>${r.wait}</span></div><div class="l2">${r.head}</div>
      <div class="chips"><span class="badge ${r.risk[0]}">${r.risk[1]}</span><span class="tk-mono-chip">${r.ref}</span><span class="t-hint">${r.conf}</span></div></div></div>`).join('')}</div>`
  const decision = `<div class="tk-pane">
    <div class="tk-dpane-head"><div class="meta"><span class="tk-mono-chip">WEB-11</span>1 of 3 · waiting 18 min <span class="badge badge-warning"><span class="dot"></span>Pending</span></div><h2>Approve design: EU shipping calculator in the cart</h2></div>
    <div class="tk-dpane-body">
      <dl class="tk-facts" style="margin:0"><div><dt>Task</dt><dd>WEB-11</dd></div><div><dt>Assignee</dt><dd>Maya Kowalczyk</dd></div><div><dt>Size</dt><dd>Large · design</dd></div><div><dt>Slices</dt><dd>3 PRs</dd></div></dl>
      <div class="tk-reco"><span class="tile">${ic('sparkles')}</span><div><b>Estimate from a zone table in the storefront</b><div class="t-hint">${AGENT} recommends</div></div><span class="conf">82%</span></div>
      <div class="tk-callout">${ic('warn')}<div><b>Needs a decision</b><div class="muted">This decision is gated to a human. Approve to let the workflow resume, edit the payload before executing, or reject with a reason.</div></div></div>
      <div><h3 class="tk-section-title">Options the agent considered</h3><div class="stack-2">
        <div class="tk-option is-picked"><span class="radio"></span><div><b>A. Zone table in the storefront</b><div class="muted">Countries grouped into 4 zones, parcel size from product dimensions. No new integration; the table is edited in the admin.</div></div></div>
        <div class="tk-option"><span class="radio"></span><div><b>B. Live carrier rates API</b><div class="muted">Exact prices, but needs a carrier contract the task rules out.</div></div></div>
      </div></div>
      <div><h3 class="tk-section-title">Proposed slices</h3><ol class="tk-slices"><li>Zone table entity and admin page</li><li>Estimate endpoint and cart widget</li><li>Checkout uses the same table; copy explains any difference</li></ol></div>
    </div>
    <div class="tk-dpane-foot"><button class="btn btn-outline">${ic('x')}Reject <span class="kbd">R</span></button><button class="btn btn-outline">${ic('pencil')}Edit <span class="kbd">E</span></button><button class="btn btn-primary">${ic('check')}Approve <span class="kbd">A</span></button></div>
  </div>`
  const head = `<div class="page-head"><div><h1 class="t-page-title">Caseload</h1><p>3 in the shared queue · sorted by: waiting time</p></div>${mobile ? '' : `<div class="page-actions"><div class="segmented"><button aria-selected="true">Inbox</button><button>List</button></div><button class="btn btn-outline btn-icon">${ic('rotate')}</button></div>`}</div>`
  const tiles = `<div class="tk-tiles">${[['inbox', 'Needs action', 3, 'pending proposals awaiting a decision'], ['clock', 'Waiting', 0, 'on third party or customer'], ['activity', 'Running', 2, 'agents working — no action']].map(([i, l, n, d]) => `<div class="tk-tile"><span class="l">${ic(i)}${l}</span><span class="n">${n}</span>${mobile ? '' : `<span class="d">${d}</span>`}</div>`).join('')}</div>`
  return mobile
    ? `<div class="page" style="gap:1rem">${head}${tiles}${decision}</div>`
    : `<div class="page">${head}${tiles}<div class="tk-cl">${queue}${decision}</div></div>`
}

// ── product page behind the chat, and the chat itself ───────────────────
function productPage(mobile) {
  return `<div class="page"><div class="page-head"><div><h1 class="t-page-title">Oak dining table 180</h1><p>SKU NW-OAK-180 · Published</p></div>${mobile ? '' : `<div class="page-actions"><button class="btn btn-outline">Preview</button><button class="btn btn-primary">Save</button></div>`}</div>
    <div class="form-layout" style="display:grid;grid-template-columns:${mobile ? '1fr' : '7fr 3fr'};gap:1rem">
      <div class="card card-pad stack-3"><div class="t-label" style="font-weight:500">General</div>
        <div class="field"><label>Name</label><input class="input" value="Oak dining table 180" /></div>
        <div class="field"><label>Description</label><textarea class="textarea">Solid European oak, oiled finish. Seats 6, or 8 with the extension leaf.</textarea></div></div>
      <div class="card card-pad stack-3"><div class="t-label" style="font-weight:500">Pricing</div>
        <div class="field"><label>Price (EUR)</label><input class="input" value="1,390.00" /></div>
        <span class="t-hint">Changed from 1,290.00 on 1 Sep 2026</span></div>
    </div></div>`
}
const msg = (who, html) => `<div class="tk-msg${who === 'ai' ? ' ai' : ''}"><span class="av">${ic(who === 'ai' ? 'bot' : 'user')}</span><div class="c"><span class="role">${who === 'ai' ? 'Assistant' : 'You'}</span>${html}</div></div>`
const tools = (rows) => `<div class="tk-tools"><div class="tk-tools-head">${ic('wrench')}Tool calls<span class="n">${rows.length}</span></div>${rows.map(([name, caption]) => `<div class="tk-tool">${ic('chevron-right')}${ic('wrench')}<code>${name}</code><span class="muted">${caption}</span><span class="st">done</span></div>`).join('')}</div>`
function mutationCard({ canDelegate = true } = {}) {
  const rows = [
    ['project', 'WEB · Company website'],
    ['title', 'Update Oak dining table price on the product page'],
    ['body', 'The website shows €1,290 for Oak dining table 180 (NW-OAK-180); the catalog price is €1,390 since 1 Sep 2026. Update the product page. Done when the page matches the catalog price.'],
    ['priority', 'High'],
    ['assignee', 'Maya Kowalczyk (you)'],
    ['delegate', canDelegate ? AGENT : '—'],
  ]
  return `<div class="tk-mut">
    <div class="tk-mut-head">${ic('shield')}<div><b>Review proposed changes</b><span>${canDelegate ? 'Creates 1 task in WEB and starts a factory run.' : 'Creates 1 task in WEB. You can’t delegate to agents, so it waits in Open.'}</span></div></div>
    <table class="tk-diff"><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>${rows.map(([f, a]) => `<tr><td class="f">${f}</td><td class="muted">—</td><td class="a">${esc(a)}</td></tr>`).join('')}</tbody></table>
    <div class="tk-mut-foot"><button class="btn btn-ghost btn-sm">${ic('eye')}Review details</button><span class="grow"></span><button class="btn btn-outline btn-sm">Cancel</button><button class="btn btn-primary btn-sm">Confirm</button></div>
  </div>`
}
function chat(stage) {
  const intro = [
    msg('you', `<p>The product page on our website still shows last year’s price for this table. Can you get it fixed?</p>`),
    msg('ai', `${tools([['task_tools.list_projects', '2 projects'], ['task_tools.search_tasks', 'no open task matches “Oak dining table price”']])}<p>Which site is it on: the main website (<b>WEB</b>) or the B2B shop (<b>B2B</b>)?</p>`),
    msg('you', `<p>Main website.</p>`),
  ]
  const propose = msg('ai', `<p>Here is the task. Confirm to create it and hand it to the ${AGENT}; you stay the owner.</p>${mutationCard()}`)
  const after = [
    msg('ai', `<div class="alert alert-success">${ic('check-circle')}<div><div class="alert-title">Action applied</div><div>WEB-13 was created and delegated to the ${AGENT}.</div><div class="tk-inline-links" style="margin-top:0.375rem"><a class="btn btn-outline btn-xs">View task WEB-13 ${ic('external')}</a></div></div></div><p>From here it runs on the board. You’ll get a Caseload item if the agent needs a decision.</p>`),
    msg('you', `<p>What’s happening with WEB-11?</p>`),
    msg('ai', `${tools([['task_tools.get_task', 'WEB-11'], ['tasks.get_delegation', 'WEB-11']])}<p><b>WEB-11 · Add EU shipping calculator to checkout</b> is <b>In design</b>. The ${AGENT}’s plan has been waiting for your approval in the Caseload for 18 minutes: it recommends a zone table in the storefront, in 3 PRs.</p><div class="tk-inline-links"><a class="btn btn-primary btn-xs">Open in Caseload</a><a class="btn btn-outline btn-xs">Open task</a></div>`),
  ]
  const msgs = stage === 'propose' ? [...intro, propose] : [...intro.slice(0, 1), msg('ai', `<p class="muted" style="font-size:0.75rem">…3 earlier messages</p>`), ...after]
  return `<div class="tk-chat">
    <div class="tk-chat-top"><span class="tk-ctx">${ic('package')}Product · Oak dining table 180</span><button class="icon-btn" title="Start new conversation">${ic('plus')}</button></div>
    <div class="tk-msgs">${msgs.join('')}</div>
    <div class="tk-composer"><div class="textarea">Ask anything…</div><div class="tk-composer-row"><button class="icon-btn" title="Attach file">${ic('paperclip')}</button><span class="grow">Press Enter to send, Shift+Enter for new line.</span><button class="btn btn-primary btn-sm">${ic('send')}Send</button></div></div>
  </div>`
}
function dock(stage, mobile) {
  const head = `<div class="tk-dock-head">${mobile ? `<button class="icon-btn">${ic('chevron-left')}</button>` : ''}<div class="grow"><div class="t"><span class="ai-dot"></span>Task intake <span class="tk-beta">Beta</span></div><div class="d">Turns a request into a task on the board</div></div>${mobile ? '' : `<button class="icon-btn" title="Collapse AI dock">${ic('minimize')}</button>`}<button class="icon-btn" title="Close AI dock">${ic('x')}</button></div>`
  return mobile ? `<div class="tk-sheet">${head}${chat(stage)}</div>` : `<aside class="tk-dock">${head}${chat(stage)}</aside>`
}

// ── drawer fixtures per state ───────────────────────────────────────────
const tl = {
  web14: [{ text: 'Created by Maya Kowalczyk', at: '16 Sep, 10:02', on: true }],
  web11: [
    { text: 'Created by Maya Kowalczyk', at: '09:12' }, { text: `Delegated to ${AGENT}`, at: '09:14' }, { text: 'Queued · run started', at: '09:14' },
    { text: 'Sized: large, design first', at: '09:21' }, { text: 'Plan ready · waiting for approval in Caseload', at: '09:40', on: true },
  ],
  web9: [
    { text: `Delegated to ${AGENT}`, at: '16 Sep, 14:05' }, { text: 'Sized: small, no design gate', at: '14:09' }, { text: 'In progress · slice 1 of 1', at: '14:09' },
    { text: 'PR #48 opened · CI green', at: '14:52' }, { text: 'Review agent: approve with 1 follow-up', at: '15:10', on: true },
  ],
  web6: [
    { text: `Delegated to ${AGENT}`, at: '15 Sep, 11:30' }, { text: 'Design approved by Tomasz Lis', at: '12:02' }, { text: 'PR #44 opened · CI red', at: '12:48' },
    { text: 'Fix round 1 · CI red', at: '13:15' }, { text: 'Failed · delegate released', at: '13:15', on: true },
  ],
}

// ── screens: one entry per state ────────────────────────────────────────
const BOARD_URL = '/backend/tasks?project=WEB'
const screens = [
  {
    id: 's1', nav: 'Empty', title: 'Board, no project yet',
    task: 'An admin opens Tasks for the first time; nothing can be created until a project exists.',
    refs: ['SPEC-002 · User stories (empty board)', 'Design · Projects'],
    html: both((mobile) => shell({ url: '/backend/tasks', mobile, nav: 'tasks', crumbs: ['Tasks'],
      page: `<div class="page">${boardHead(mobile, true)}<div class="empty" style="padding:4rem 1.5rem"><div class="empty-icon">${ic('folder')}</div><b>No projects yet</b><span class="muted" style="max-width:26rem">Tasks live in projects. A project gives each task a reference like <b>WEB-12</b> and, for the factory, the repository it works in.</span><button class="btn btn-primary">${ic('plus')}Create project</button></div></div>` })),
    notes: [
      '“New task” stays disabled with a tooltip until a project exists; the call to action goes to <code>/backend/tasks/projects</code> (key, name, default assignee, repo URL).',
      'Once a project exists the board renders its empty columns with “New task” in Open, not this screen.',
    ],
  },
  {
    id: 's2', nav: 'Board', title: 'Board, a normal day',
    task: 'Ada, the team lead, sees everything in WEB by status: human work, delegated work and the one decision waiting on a human.',
    refs: ['SPEC-002 · Design · Board', 'Run state table', 'SPEC-001 · Status lifecycle'],
    html: both((mobile) => shell({ url: BOARD_URL, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], page: board({ focus: 'WEB-14', mobileCol: 'in_design' }, mobile) })),
    notes: [
      'The badge next to the agent mark is the <b>derived run state</b> (starting, running, needs decision, complete); the column is the task status. Both refresh on client-broadcast events, no reload.',
      'Delegated cards can’t be dragged (409 <code>process_owned</code>), except the assignee closing an In review card. WEB-8 is human work with a PR and drags freely.',
      '“Needs decision” links to the Caseload item. Closed (done, rejected, failed) is a collapsed column; clicking it expands one list with close reasons.',
      'Mobile: one lane at a time, picked from the status strip; there is no drag on mobile, status moves go through the drawer.',
    ],
  },
  {
    id: 's3', nav: 'No results', title: 'Board, filters match nothing',
    task: 'Ada narrows the board to urgent delegated work for Tomasz and there is none.',
    refs: ['SPEC-002 · Design · filter bar'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&assignee=tl&delegate=1&priority=urgent`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'],
      page: board({ noResults: true, filters: ['Assignee: Tomasz Lis', 'Has delegate', 'Priority: Urgent'] }, mobile) })),
    notes: ['Filters live in the URL, so a filtered board can be shared. The columns are replaced by one empty state rather than five empty columns.'],
  },
  {
    id: 's4', nav: 'New task', title: 'New task dialog',
    task: 'Maya writes down a request for the website. Creating a task never starts anything.',
    refs: ['SPEC-002 · Design · New task dialog', 'User stories · Product owner'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&new=1`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '52rem',
      page: board({}, mobile), overlay: newTaskDialog(mobile), overlayKind: 'modal' })),
    notes: [
      'No delegate field here on purpose: delegation is a separate, audited step with its own permission, done from the card or drawer (<span class="kbd">D</span>).',
      'The assignee defaults to the current user or the project’s default assignee. The reference is allocated on save; the subtitle shows the next one.',
    ],
  },
  {
    id: 's5', nav: 'Delegate', title: 'Drawer, handing the task to the Factory agent',
    task: 'Maya opens WEB-14 and presses D to delegate it; she remains the accountable assignee.',
    refs: ['SPEC-002 · Delegation 1–2', 'User stories · Product owner'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&task=WEB-14`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '46rem', page: board({ focus: 'WEB-14', mobileCol: 'open' }, mobile),
      overlay: drawer(T.web14, { delegatePicker: 'open', links: [{ icon: 'paperclip', label: 'room-clearance.pdf', sub: 'Attachment · 212 KB' }], timeline: tl.web14 }, mobile) })),
    notes: [
      'Picking the agent sets the status to Queued and emits <code>tasks.task.delegated</code>; within a second the card shows “Starting…”.',
      'The picker lists agent principals from <code>GET /api/tasks/agents</code>. Title and body stay editable only while the task is Open.',
    ],
  },
  {
    id: 's6', nav: 'No permission', title: 'Drawer, user without tasks.delegate',
    task: 'Tomasz’s colleague can create and edit tasks but not hand them to an agent.',
    refs: ['SPEC-002 · User stories (picker disabled)', 'ACL · tasks.delegate'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&task=WEB-14`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '44rem', page: board({ focus: 'WEB-14', mobileCol: 'open' }, mobile),
      overlay: drawer(T.web14, { delegatePicker: 'disabled', timeline: tl.web14 }, mobile) })),
    notes: ['The picker is shown disabled with the reason, not hidden, so people learn delegation exists and who to ask.'],
  },
  {
    id: 's7', nav: 'Factory down', title: 'Drawer, delegation refused: orchestrator unavailable',
    task: 'Maya delegates, but the factory.deliver process is missing or disabled in this tenant.',
    refs: ['SPEC-002 · Delegation 1', 'API · 503 orchestrator_unavailable'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&task=WEB-14`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '44rem', page: board({ focus: 'WEB-14', mobileCol: 'open' }, mobile),
      overlay: drawer(T.web14, { timeline: tl.web14, alert: `<div class="alert alert-error">${ic('alert-circle')}<div><div class="alert-title">The factory isn’t available</div><div>The <code>factory.deliver</code> process is missing or disabled, so nothing was started. The task stays Open. An admin can enable it under Processes.</div></div></div>` }, mobile) })),
    notes: ['The refusal is synchronous: no task can sit in Queued waiting for a run that will never start. Nothing was written; retrying later is safe.'],
  },
  {
    id: 's8', nav: 'Stalled', title: 'Board, a delegation nobody picked up',
    task: 'WEB-13 has been Starting for more than 60 seconds; Maya can take it back.',
    refs: ['SPEC-002 · Run state (stalled)', 'Delegation 4'],
    html: both((mobile) => shell({ url: BOARD_URL, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], page: board({ stalled: true, focus: 'WEB-13', mobileCol: 'queued' }, mobile) })),
    notes: [
      '“Stalled” means the start subscriber or <code>startExecution</code> failed. Un-delegate is always allowed before a run is linked; it returns the task to Open.',
      '“Details” opens the drawer with the delegation time and a link to the orchestrator’s Processes page.',
    ],
  },
  {
    id: 's9', nav: 'In design', title: 'Drawer, the plan waits for a human',
    task: 'Maya opens WEB-11: the agent has sized it large and its design is waiting in the Caseload. She tries to take it back.',
    refs: ['SPEC-002 · Delegation 4', 'API · 409 decision_pending', 'SPEC-001 · WSFF gate'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&task=WEB-11`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '57rem', page: board({ focus: 'WEB-11' }, mobile),
      overlay: drawer(T.web11, {
        alert: `<div class="alert alert-warning">${ic('inbox')}<div><div class="alert-title">Your decision is needed</div><div>The ${AGENT} proposed a design 18 minutes ago. Approve or reject it in the Caseload.</div><div style="margin-top:0.5rem"><a class="btn btn-primary btn-xs">Open in Caseload</a></div></div></div>`,
        links: [{ icon: 'workflow', label: 'Process run factory.deliver #a41f', sub: 'Running · cost so far $0.84', right: ic('external') }, { icon: 'inbox', label: 'Caseload: Approve design', sub: 'Pending · 18 min', right: ic('external') }],
        timeline: tl.web11,
        comments: [{ who: 'MK', at: '09:30', text: 'Only EU countries for now; the UK is out of scope.' }],
        toast: `<div class="toast tk-toast-left">${ic('info')}<span>Can’t un-delegate: the plan is already sized. Reject it in the Caseload instead.</span><a class="btn btn-ghost btn-xs">Open</a></div>`,
      }, mobile) })),
    notes: [
      'After the <code>sized</code> milestone, un-delegating returns 409 <code>decision_pending</code> with the instance link; the toast turns that into the next step.',
      'Comments are context for the agent (read via <code>task_tools.get_task</code>), treated as untrusted input like the body.',
    ],
  },
  {
    id: 's10', nav: 'Caseload', title: 'Caseload, approving the design (orchestrator screen, illustrative)',
    task: 'Maya reviews the plan, not a diff: options considered, the recommendation, and the slices that will become PRs.',
    refs: ['SPEC-001 · The process (design gate)', 'Orchestrator · Caseload'],
    html: both((mobile) => shell({ url: '/backend/caseload', mobile, nav: 'caseload', crumbs: ['Agents', 'Caseload'], page: caseload(mobile) })),
    notes: [
      'This is the Agent Orchestrator’s own page; we build nothing here. Drawn so the flow reads end to end, with our fixtures in it.',
      'Approve resumes the process: the task moves to In progress and the card shows Running. Reject asks for a reason and closes the task as Rejected.',
      'The Legal reviewer row shows change-class routing from SPEC-001: legal text goes to a legal reviewer, who never sees GitHub.',
    ],
  },
  {
    id: 's11', nav: 'In review', title: 'Drawer, PR open, review done, follow-ups filed',
    task: 'Maya checks WEB-9: the PR and preview are ready, the review agent filed a follow-up, and she closes the task after the merge.',
    refs: ['SPEC-002 · Follow-ups', 'Who writes status (assignee closes In review)', 'SPEC-001 · Previews per run'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&task=WEB-9`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '54rem', page: board({ focus: 'WEB-9', mobileCol: 'in_review' }, mobile),
      overlay: drawer(T.web9, {
        links: [
          { icon: 'pr', label: 'PR #48 · feat(products): Linden bench page', sub: 'Open · CI green · review agent approved', right: ic('external') },
          { icon: 'globe', label: 'Preview · pr-48.preview.northwind.example', sub: 'Deployed 14:58', right: ic('external') },
          { icon: 'workflow', label: 'Process run factory.deliver #9c02', sub: 'Complete · $1.92', right: ic('external') },
        ],
        followups: `<div class="tk-links"><div class="tk-link">${ic('child')}<div class="grow"><div>WEB-16 · Add alt text to Linden bench gallery images</div><div class="t-hint">Open · Maya Kowalczyk · no delegate</div></div>${statusBadge('open')}</div></div>`,
        timeline: tl.web9,
        foot: `<button class="btn btn-outline">Reject…</button><button class="btn btn-primary">${ic('check')}Close as done</button>`,
      }, mobile) })),
    notes: [
      'MVP has no PR-merged hook, so the assignee may close an In review task even while it is delegated; that releases the delegate.',
      'Follow-ups keep the parent’s assignee and get <b>no delegate</b>: only a person starts new work, so the factory can’t feed itself.',
    ],
  },
  {
    id: 's12', nav: 'Failed', title: 'Drawer, a run that failed',
    task: 'Tomasz opens WEB-6 after CI failed twice; he reads the reason and reopens it to try again.',
    refs: ['SPEC-002 · Delegation 6–7', 'SPEC-001 · one bounded CI fix round'],
    html: both((mobile) => shell({ url: `${BOARD_URL}&task=WEB-6`, mobile, nav: 'tasks', crumbs: ['Tasks', 'WEB · Company website'], tall: '46rem', page: board({}, mobile),
      overlay: drawer(T.web6, {
        createdBy: 'TL',
        alert: `<div class="alert alert-error">${ic('x-circle')}<div><div class="alert-title">Failed</div><div>${esc(T.web6.reason)}</div></div></div>`,
        links: [{ icon: 'pr', label: 'PR #44 · feat(stock): read badges from warehouse feed', sub: 'Open · CI red', right: ic('external') }, { icon: 'activity', label: 'Trace of the failed step', sub: '$2.31', right: ic('external') }],
        timeline: tl.web6,
        foot: `<button class="btn btn-primary">${ic('rotate')}Reopen</button>`,
      }, mobile) })),
    notes: [
      'A failed task has its delegate released. Reopen returns it to Open; delegating again gives a new <code>delegationId</code>, so a new run, and late writes from the old run are dropped.',
      'The same state is reached when someone cancels the run from the orchestrator’s UI (safety-net subscriber).',
    ],
  },
  {
    id: 's13', nav: 'Chat: request', title: 'Chat intake, from a vague request to a task proposal',
    task: 'Maya is on the product in the catalog, opens the AI assistant (⌘L), picks Task intake and describes the problem in her own words.',
    refs: ['SPEC-002 · Chat intake', 'User stories · Business owner (chat)'],
    html: both((mobile) => shell({ url: '/backend/catalog/products/nw-oak-180', mobile, nav: 'products', crumbs: ['Catalog', 'Products', 'Oak dining table 180'], dock: dock('propose'), tall: '62rem',
      page: productPage(mobile), overlay: mobile ? dock('propose', true) : null })),
    notes: [
      'No new chat UI: this is OM 0.8’s AI dock and <code>AiChat</code>. We add one agent (<code>tasks.intake</code>) and one write tool (<code>tasks_create</code>).',
      'The product chip is an attached record: 0.8 attaches nothing automatically, so Maya attached it. The agent quotes it in the body.',
      'The card is OM’s standard mutation approval (<code>prepareMutation</code>): nothing is written before Confirm, and it runs the board’s own create and delegate commands as Maya.',
      'Without <code>tasks.delegate</code> the card reads “Creates 1 task in WEB. You can’t delegate to agents, so it waits in Open.” and the delegate row is empty.',
    ],
  },
  {
    id: 's14', nav: 'Chat: after', title: 'Chat intake, confirmed; then asking about another task',
    task: 'Maya confirms, gets a link to WEB-13, then asks what is happening with WEB-11.',
    refs: ['SPEC-002 · Chat intake', 'AI tools · task_tools.get_task'],
    html: both((mobile) => shell({ url: '/backend/catalog/products/nw-oak-180', mobile, nav: 'products', crumbs: ['Catalog', 'Products', 'Oak dining table 180'], dock: dock('after'), tall: '52rem',
      page: productPage(mobile), overlay: mobile ? dock('after', true) : null })),
    notes: [
      'The chat hands off: progress, the design gate and the PR live on the board, the drawer and the Caseload, never as a stream in the chat.',
      '<code>source=chat</code> with the conversation and message id as <code>source_ref</code>, so a retried Confirm can’t create WEB-13 twice.',
      'Status questions are read-only (<code>task_tools.get_task</code>, <code>tasks.get_delegation</code>, <code>task_tools.search_tasks</code>) and answer with links, not copies of the plan.',
    ],
  },
]

// ── document ────────────────────────────────────────────────────────────
const html = `<!doctype html>
<html lang="en" data-prototype-id="${PROTOTYPE_ID}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Factory intake — storyboard</title>
<link rel="stylesheet" href="tokens.css" />
<link rel="stylesheet" href="components.css" />
<link rel="stylesheet" href="screens.css" />
<link rel="stylesheet" href="prototype.css" />
</head>
<body>
${sprite()}
<div class="doc-toolbar">
  <strong style="font-size:0.875rem">Factory intake — storyboard</strong>
  <nav class="screen-nav" aria-label="Screens">${screens.map((s, i) => `<a href="#${s.id}">${i + 1} ${esc(s.nav)}</a>`).join('')}</nav>
  <button class="btn btn-outline btn-sm" id="theme-toggle" type="button">${ic('sun')} Theme</button>
</div>
<div class="doc">
<header class="doc-head">
  <h1>Factory intake — every state, both widths</h1>
  <p class="muted" style="max-width:70ch;margin:0">Storyboard for <code class="t-mono">docs/specs/SPEC-002-2026-09-18-tasks-module.md</code>. Each section is one state, rendered at desktop (1280) and mobile (390) from one fixture set. All data is fictional. Read top to bottom; nothing needs clicking.</p>
</header>
${screens.map((s, i) => `
<section class="screen" id="${s.id}">
  <div class="screen-meta">
    <h2>${i + 1}. ${esc(s.title)}</h2>
    <p>${esc(s.task)}</p>
    <div class="screen-refs">${s.refs.map((r) => `<span class="ref">${esc(r)}</span>`).join('')}</div>
  </div>
  ${s.html}
  <div class="notes">${s.notes.map((n, j) => `<div class="note"><b>${j + 1}</b><span>${n}</span></div>`).join('')}</div>
</section>`).join('\n')}
</div>
<script>
(function () { var btn = document.getElementById('theme-toggle'); btn.addEventListener('click', function () { document.documentElement.classList.toggle('dark'); }); })();
</script>
<script src="comments.js"></script>
<script src="prototype.js"></script>
</body>
</html>
`
try {
  syncComments()
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
}
fs.writeFileSync(path.join(OUT, 'index.html'), html)
console.log('wrote index.html', html.length, 'chars,', screens.length, 'screens')
